version: '3'

services:

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 3030:8080

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1529164
      - MYSQL_DATABASE=kien
      - MYSQL_USER=kien
      - MYSQL_PASSWORD=1529164